config/routes.rb
Rails.application.routes.draw do
  resources :answers
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'profile', to: 'user#profile'
  get 'carts/destroy' => 'carts#destroy'

  devise_for :users
  resources :products do
    resources :comments do
      resources :answers
    end
  end
  resources :carts

  resources :order_products
  resources :orders

  root to: 'products#index'
end

app/models/Product.rb
class Product < ApplicationRecord
    
  belongs_to :user
  has_many :comments, dependent: :destroy

  resourcify

  def self.search(search_term)
    if search_term
      where('name LIKE ?', "%#{search_term.downcase}%")
    else
      all
    end
  end

  def rating
    sum = 0.0
    unless self.comments.count == 0
      self.comments.to_a.each {|comment| sum += comment.rating}
      sum /= self.comments.count
    end
    sum
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy

  def add (product)
    item = cart_items.find_by(product_id: product.id)
    if item
      item.quantity += 1
    else
      item = cart_items.build(product_id: product.id) 
    end
    item
  end

  def total 
    cart_items.sum {|item| item.sum_price}
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def sum_price
    product.price * quantity
  end 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product

  has_many :answers, dependent: :destroy
end

app/models/jewel.rb
class Jewel < ApplicationRecord
  validates :name, :size, :price, presence: true
  validates :size, inclusion: { in: 17..30, message: "should be between 17 and 30" }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products, dependent: :destroy

  enum pay_types: {
    cash: 'Cash',
    credit_card: 'Credit Card',
    check: 'Check'
  }
  enum statuses: {
    not_staged: 'Not staged',
    in_progress: 'In progress',
    ready: 'Ready'
  }
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.search(search_term)
    if search_term
      where('name LIKE ?', "%#{search_term.downcase}%")
    else
      all
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy
  after_create :assign_default_role

  def assign_default_role
    add_role(:customer) if roles.blank?
  end

  def admin?
    has_role? :admin
  end

  def manager?
    has_role? :manager
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  expose :comment
  expose :answer, scope: -> { comment.answers }

  expose :answers, from: :comment

  before_action :authorize_answer

  def create
    answer.user = current_user

    answer.save
    respond_with answer, location: comment.product
  end

  def update
    answer.update(answer_params)
    respond_with answer, location: comment.product
  end

  def destroy
    answer.destroy
    respond_with answer, location: comment.product
  end

  private

  def authorize_answer
    authorize answer
  end

  def answer_params
    params.require(:answer).permit(:text, :user_id, :comment_id)
  end
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart # for set_cart and sort_cart method
  expose :product
  expose(:cart) { set_cart }
  expose(:sorted_cart) { sort_cart }

  def create
    cart << product.id
    redirect_to carts_path
  end

  def destroy
    cart.delete(product.id)
    redirect_to carts_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose :product
  expose :comments, from: :product
  expose :comment, scope: -> { product.comments }

  expose :answers, from: :comment

  before_action :authorize_comment

  def create
    comment.user = current_user

    comment.save
    respond_with comment, location: product
  end

  def update
    comment.update(comment_params)
    respond_with comment, location: product
  end

  def destroy
    comment.destroy
    respond_with comment, location: product
  end

  private

  def authorize_comment
    authorize comment
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:rating, :text)
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  private

    def set_cart
      session[:cart] || session[:cart] = []
    end

    def sort_cart
      cart.each_with_object(Hash.new(0)) { |product, quantity| quantity[product] += 1; }
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart # for set_cart and sort_cart method
  expose_decorated :order
  expose(:orders) { Order.all }
  expose :order_products, from: :order

  expose(:cart) { set_cart }
  expose(:sorted_cart) { sort_cart }

  before_action :authorize_order

  def create
    order.user = current_user
    if order.save
      CreateOrderProductsFromCart.call(order: order, cart: sorted_cart)
      OrderCreateNotification.call(order: order)
    end
    respond_with order, location: profile_path
  end

  # update order.status
  def update
    if order.update(order_status)
      OrderUpdateStatusNotification.call(order: order)
    end
    respond_with order, location: orders_path
  end

  def destroy
    order.destroy
    respond_with order, location: profile_path
  end

  private

  def authorize_order
    authorize order
  end

  def order_params
    params.require(:order).permit(:name, :phone_number, :email, :address, :pay_type)
  end

  def order_status
    params.require(:order).permit(:status)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  expose_decorated(:product)
  expose(:products) { find_sort_products }
  def create
    product.user = current_user

    product.save
    CreateImageForProduct.call(product: product, image: params[:image])
    respond_with product
  end

  def update
    product.update(product_params)
    CreateImageForProduct.call(product: product, image: params[:image])
    respond_with product
  end

  def destroy
    product.destroy
    respond_with product
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def find_sort_products
    Product.search(params[:search_term]).all.decorate.sort_by(&:rating).reverse
  end

  def product_params
    params.require(:product).permit(:name, :desc, :style, :size, :image, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  before_action :delete_cart, only: [:destroy]

  private 
    def delete_cart
      CartItem.where(cart_id: session[:cart_id]).delete_all
      Cart.where(id: session[:cart_id]).delete_all
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def profile; end
end

app/views/answers/_answer.html.slim
#answer
  p
    strong Author:
    = answer.user.email
  p
    strong Answer:
    = answer.text
  - if current_user.try(:admin?) || answer.user == current_user
    = link_to 'Edit', edit_product_comment_answer_path(answer.comment.product, answer.comment, answer)
    |  | 
    = link_to 'Delete', product_comment_answer_path(answer.comment.product, answer.comment, answer), method: :delete, data: { confirm: 'Are you sure?' }
  br

app/views/answers/_form.html.slim
= form_for([comment.product, comment, answer]) do |f|
  .field
    = f.label :text
    = f.text_field :text
  .actions
    = f.submit

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/cart_items/_cart_item.html.slim
#cart_item
  tr
    td = cart_item.product.name
    td = cart_item.product.desc
    td = cart_item.quantity
    td
      = number_to_currency(cart_item.sum_price)
    td = link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' }

app/views/carts/index.html.slim
h1 Cart Items
table
  thead
    tr
      th quantity
      th product
      th price
      th colspan="3" 
  tbody
    - sorted_cart.each do |id, quantity|
      tr
        td= quantity
        td= Product.find(id).name
        td= number_to_currency(Product.find(id).price * quantity)
        td= link_to 'Destroy', carts_destroy_path(product_id: id)
= link_to 'Make an order', new_order_url

app/views/comments/_comment.html.slim
#comment
  p
    strong Author:
    = comment.user.email
  p
    strong Rating:
    = comment.rating
  p
    strong Comment:
    = comment.text
  - if current_user.try(:manager?) || comment.user == current_user
    = link_to 'Edit', edit_product_comment_path(comment.product, comment)
    |  | 
    = link_to 'Delete', product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' }
  br
  #answersBlock
    p 
      strong Answers:
    = render comment.answers

    - if current_user.try(:manager?)  
      = render 'answers/form', comment: comment, answer: comment.answers.build
hr

app/views/comments/_form.html.slim
= form_for([product, comment]) do |f|
  .field
    = f.label :rating
    = f.select :rating, [['horrible', 1], ['poor', 2], ['mediocre', 3], ['good', 4], ['great', 5]]
  .field
    = f.label :text
    = f.text_field :text
  .actions
    = f.submit

app/views/comments/edit.html.slim
= render ('form'), product: comment.product
= link_to 'Back', product

app/views/jewels/_form.html.erb
<%= form_with(model: jewel, local: true) do |form| %>
  <% if jewel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jewel.errors.count, "error") %> prohibited this jewel from being saved:</h2>

      <ul>
      <% jewel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <script src="/assets/fabric.js"></script>
  <script src="/assets/funcs.js"></script>

  <div id="content"> 
  <div id="upperContent">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :jewel_name %>
    </div>

    <div class="field">
      <%= form.label :desc %>
      <%= form.text_area :desc, id: :jewel_desc %>
    </div>
    <div class="row">

      <div id="leftContent" class="col-3">

        <div id="jewType">
          <div>Выберите проектируемое изделие:</div>
          <%= form.select(:jewel_type, options_for_select([["Ring", 1], ["Necklace", 2]], 1)) %>
        </div>

        <hr>

        <div id="personalParams">
          <div>Персональные параметры:</div>
          <div class="block">Размер кольца <%= form.number_field(:size, in: 17..30) %></div>
        </div>

      </div>

      <div id="canvasContent" class="col-6"> 
        <canvas id="canvas" width="500" height="400"></canvas>

      </div>

      <div id="rightContent" class="col-3">
        <div id="buyForm">
          К оплате и доставке <a href="">-&gt;</a>
        </div>
        <div id="price" class="block">
          Цена: <%= form.number_field(:price) %>
        </div>

        <hr>

        <div id="colorButtons">
          <div id="colorHeader">Цвета:</div>
          <div class="row"  class="block">
          <div id="rowButtons">
            <button id="blue"></button>
            <button id="purple"></button>
            <button id="red"></button>
            <button id="lightgreen"></button>
            <button id="grey"></button>
            <button id="grey"></button>
            <button id="aqua"></button>
            <button id="orange"></button>
            <button id="yellow"></button>
            <button id="green"></button>
          </div>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div id="elementButtons">
    <div class="row">
  
      <div id="buttonsText" class="block">
      Комбинируйте основные модули
      </div>

      <button id="squareElement">
        <img src="/assets/squares.jpg" />
      </button>

      <button id="circleElement">
        <img src="/assets/circles.jpg" />
      </button>

      <button id="pinElement">
        <img src="/assets/pins.jpg" />
      </button>

      <button id="planeElement">
        <img src="/assets/planes.jpg" />
      </button>

    </div>
  </div>

  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jewels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @jewel.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @jewel.desc %>
</p>

<p>
  <strong>Type:</strong>
  <%= @jewel.jewel_type %>
</p>

<p>
  <strong>Size:</strong>
  <%= @jewel.size %>
</p>

<p>
  <strong>Image:</strong>
  <%= @jewel.image %>
</p>

<p>
  <strong>Price:</strong>
  <%= @jewel.price %>
</p>

<%= link_to 'Edit', edit_jewel_path(@jewel) %> |
<%= link_to 'Back', jewels_path %>

app/views/orders/_form.html.slim
= form_with(model: order, local: true) do |form|
  - if order.errors.any?
    #error_explanation
      h2
        = pluralize(order.errors.count, "error")
        | prohibited this order from being saved:
      ul
        - order.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :name
    = form.text_field :name, id: :order_name
  .field
    = form.label :phone_number
    = form.text_field :phone_number, id: :order_phone_number
  .field
    = form.label :email
    = form.email_field :email, id: :order_email
  .field
    = form.label :address
    = form.text_area :address, id: :order_address
  .field
    = form.label :pay_type
    = form.select :pay_type, Order.pay_types.values, id: :order_pay_type
  .actions
    = form.submit

app/views/orders/edit.html.slim
h1 Change order status
= form_with(model: order, local: true) do |form|
  - if order.errors.any?
    #error_explanation
      h2
        = pluralize(order.errors.count, "error")
        | prohibited this order from being saved:
      ul
        - order.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :status
    = form.select :status, Order.statuses.values, id: :order_status
  .actions
    = form.submit

= link_to 'Back', orders_path

app/views/orders/index.html.slim
h1 Orders
table
  thead
    tr
      th Name
      th Phone number
      th Email
      th Address
      th Pay type
      th Order status
      th colspan="3" 
  tbody
    - orders.each do |order|
      tr
        td= order.name
        td= order.phone_number
        td= order.email
        td= order.address
        td= order.pay_type
        td= order.status
        td= link_to 'Show', order
        td= link_to 'Edit', edit_order_path(order)
        td= link_to 'Destroy', order, method: :delete

app/views/orders/new.html.slim
h1 New Order
= render 'form'
= link_to 'Back', carts_path

app/views/orders/show.html.slim
p
  strong Name:
  = order.name
p
  strong Phone number:
  = order.phone_number
p
  strong Email:
  = order.email
p
  strong Address:
  = order.address
p
  strong Pay type:
  = order.pay_type
p
  strong Change order status:
  = order.pay_type
- if order.can_be_cancelled?
  = link_to 'Cancel Order', order_path, method: :delete
| \
= link_to 'Back', profile_path

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <script src="/assets/fabric.js"></script>
  <script src="/assets/builder_funcs.js"></script>
  <script src="/assets/save_canvas_as_png.js"></script>

  <div id="builder"> 
  <div id="upperContent">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :product_name %>
    </div>

    <div class="field">
      <%= form.label :desc %>
      <%= form.text_area :desc, id: :product_desc %>
    </div>

    <input id="image" type="hidden" value="" name="image"/>
    
    <div class="row">

      <div id="leftContent" class="col-3">

        <div id="jewType">
          <div>Выберите проектируемое изделие:</div>
          <%= form.select(:style, options_for_select([["Ring", 1], ["Necklace", 2]], 1)) %>
        </div>

        <hr>

        <div id="personalParams">
          <div>Персональные параметры:</div>
          <div class="block">Размер кольца <%= form.number_field(:size, in: 17..30) %></div>
        </div>

      </div>

      <div id="canvasContent" class="col-6"> 
        <canvas id="canvas" width="500" height="400"></canvas>

      </div>

      <div id="rightContent" class="col-3">
        <div id="buyForm">
          К оплате и доставке <a href="">-&gt;</a>
        </div>
        <div id="price" class="block">
          Цена: <%= form.number_field(:price) %>
        </div>

        <hr>

        <div id="colorButtons">
          <div id="colorHeader">Цвета:</div>
          <div class="row"  class="block">
          <div id="rowButtons">
            <button id="blue"></button>
            <button id="purple"></button>
            <button id="red"></button>
            <button id="lightgreen"></button>
            <button id="grey"></button>
            <button id="grey"></button>
            <button id="aqua"></button>
            <button id="orange"></button>
            <button id="yellow"></button>
            <button id="green"></button>
          </div>
          </div>
        </div>

        <div id="saveButton">
          <button onclick="saveImg();">Save</button>
        </div>
      </div>

    </div>
  </div>

  <div id="elementButtons">
    <div class="row">
  
      <div id="buttonsText" class="block">
      Комбинируйте основные модули
      </div>

      <button id="squareElement">
        <img src="/assets/squares.jpg" />
      </button>

      <button id="circleElement">
        <img src="/assets/circles.jpg" />
      </button>

      <button id="pinElement">
        <img src="/assets/pins.jpg" />
      </button>

      <button id="planeElement">
        <img src="/assets/planes.jpg" />
      </button>

    </div>
  </div>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.slim
tr
  td
    = product.name
  td
    = product.desc
  td
    = product.style
  td
    = product.size
  td
    = product.image
  td
    = product.price
  td
    = link_to 'Show', product
  td
    = link_to 'Edit', edit_product_path(product)
  td
    = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

app/views/products/edit.html.slim
h1
  | Editing product
= render 'form'
= link_to 'Back', product_path

app/views/products/index.html.slim
h1
  | Official products
= form_tag(products_path, method: :get) do
  = text_field_tag :search_term, params[:search_term]
  = submit_tag 'Search', name: nil
table
  thead
    tr
      th
        | Name
      th
        | Desc
      th
        | Style
      th
        | Size
      th
        | Image
      th
        | Price
      th
        | Author
      th
        | Rating
      th[colspan="3"]
  tbody
    - products.each do |product|
      tr
        td
          = product.name
        td
          = product.desc
        td
          = product.style
        td
          = product.size
        td
          = product.image
        td
          = product.price
        td
          = product.user.email
        td
          = product.rating
        td
          = link_to 'Show', product
        td
          = link_to 'Add Item To My Cart', carts_path(product_id: product), method: :post

        - if current_user.try(:manager?) || product.user == current_user
          td
            = link_to 'Edit', edit_product_path(product)
          td
            = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

br

= link_to 'New product', new_product_path

app/views/products/new.html.slim
h1
  | New product
= render 'form'
= link_to 'Back', products_path

app/views/products/show.html.slim
p
  strong Name:
  = product.name
p
  strong Desc:
  = product.desc
p
  strong Type:
  = product.style
p
  strong Size:
  = product.size
p
  strong Image:
  = product.image
p
  strong Price:
  = product.price

#commentsBlock
  p 
    strong Comments:
    hr
  = render product.comments

- unless current_user.nil?  
  = render 'comments/form', comment: product.comments.build

- if current_user.try(:manager?) || product.user == current_user
  = link_to 'Edit', edit_product_path(product)
  |  | 
  = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'Back', products_path

app/views/user/profile.html.slim
h1 My Profile
p
  | Email: #{current_user.email}

p My created products:
table
  thead
    tr
      th Name
      th Desc
      th Style
      th Size
      th Image
      th Price
      th[colspan="3"]
  = render current_user.products

p My orders:
table
  thead
    tr
      th Name
      th Phone number
      th Email
      th Address
      th Pay type
      th Order status
      th colspan="3" 
  - current_user.orders.each do |order|
    tr
      td= order.name
      td= order.phone_number
      td= order.email
      td= order.address
      td= order.pay_type
      td= order.status
      td= link_to 'Show', order

= link_to 'Back', root_path